---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
    name: "all-logs"
    namespace: "cattle-logging-system"
spec:
  match:
  - exclude:
      container_names: []
      hosts: []
      labels: {}
      namespaces:
        - hest
        - hjort
        - hund
  - select:
      container_names: []
      hosts: []
      labels: {}
  filters:
  - record_transformer:
      enable_ruby: true
      records:
        - log_id: ${(0...32).map { (65 + rand(26)).chr }.join}
  globalOutputRefs:
    - "cluster-to-es"
